-- 코드를 입력하세요
SELECT USER_ID, PRODUCT_ID
FROM (
    SELECT * , COUNT(SALES_AMOUNT) AS COUNT_SALE
    FROM ONLINE_SALE 
    GROUP BY USER_ID, PRODUCT_ID
) A
WHERE A.COUNT_SALE >= 2
ORDER BY USER_ID, PRODUCT_ID DESC

# SELECT * FROM ONLINE_SALE
# ORDER BY USER_ID DESC